; New song, AKG format, v1.0.

; Generated by Arkos Tracker 2.

atic_title_Start
atic_title_StartDisarkGenerateExternalLabel

atic_title_DisarkByteRegionStart0
	db "AT20"
atic_title_DisarkPointerRegionStart1
	dw atic_title_ArpeggioTable	; The address of the Arpeggio table.
	dw atic_title_PitchTable	; The address of the Pitch table.
	dw atic_title_InstrumentTable	; The address of the Instrument table.
	dw atic_title_EffectBlockTable	; The address of the Effect Block table.
atic_title_DisarkPointerRegionEnd1


; The addresses of each Subsong:
atic_title_DisarkPointerRegionStart2
	dw atic_title_Subsong0_Start
atic_title_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
atic_title_ArpeggioTable
atic_title_DisarkPointerRegionStart3
atic_title_DisarkPointerRegionEnd3

; Declares all the Pitches.
atic_title_PitchTable
atic_title_DisarkPointerRegionStart4
atic_title_DisarkPointerRegionEnd4

; Declares all the Instruments.
atic_title_InstrumentTable
atic_title_DisarkPointerRegionStart5
	dw atic_title_EmptyInstrument
	dw atic_title_Instrument1
	dw atic_title_Instrument2
	dw atic_title_Instrument3
	dw atic_title_Instrument4
	dw atic_title_Instrument5
	dw atic_title_Instrument6
	dw atic_title_Instrument7
	dw atic_title_Instrument8
	dw atic_title_Instrument9
	dw atic_title_Instrument10
atic_title_DisarkPointerRegionEnd5

atic_title_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
atic_title_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

atic_title_Instrument1
	db 4	; The speed (>0, 0 for 256).
	db 225	; Soft only. Volume: 12. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 49	; Soft only. Volume: 6.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 169	; Soft only. Volume: 5. Volume only.

	db 33	; Soft only. Volume: 4.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 153	; Soft only. Volume: 3. Volume only.

	db 17	; Soft only. Volume: 2.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -2	; Pitch.

atic_title_Instrument1_Loop	db 9	; Soft only. Volume: 1.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 17	; Soft only. Volume: 2.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 3	; Pitch.

	db 9	; Soft only. Volume: 1.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 17	; Soft only. Volume: 2.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -3	; Pitch.

	db 7	; Loop.
atic_title_DisarkWordForceReference6
	dw atic_title_Instrument1_Loop	; Loop here.

atic_title_Instrument2
	db 4	; The speed (>0, 0 for 256).
	db 201	; Soft only. Volume: 9. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 33	; Soft only. Volume: 4.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 153	; Soft only. Volume: 3. Volume only.

	db 17	; Soft only. Volume: 2.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 137	; Soft only. Volume: 1. Volume only.

	db 0	; No Soft no Hard. Volume: 0. Noise? false.

atic_title_Instrument2_Loop	db 9	; Soft only. Volume: 1.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 9	; Soft only. Volume: 1.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 7	; Loop.
atic_title_DisarkWordForceReference7
	dw atic_title_Instrument2_Loop	; Loop here.

atic_title_Instrument3
	db 3	; The speed (>0, 0 for 256).
	db 17	; Soft only. Volume: 2.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -5	; Arpeggio.

	db 33	; Soft only. Volume: 4.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -4	; Arpeggio.

	db 49	; Soft only. Volume: 6.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -3	; Arpeggio.

	db 65	; Soft only. Volume: 8.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -2	; Arpeggio.
	dw 1	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -1	; Arpeggio.

	db 97	; Soft only. Volume: 12.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db 3	; Arpeggio.
	dw -1	; Pitch.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 7	; Arpeggio.

	db 121	; Soft only. Volume: 15.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db 12	; Arpeggio.
	dw 1	; Pitch.

	db 113	; Soft only. Volume: 14.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db 12	; Arpeggio.
	dw -1	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db 12	; Arpeggio.
	dw 2	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db 12	; Arpeggio.
	dw -2	; Pitch.

	db 65	; Soft only. Volume: 8.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db 9	; Arpeggio.
	dw 3	; Pitch.

	db 49	; Soft only. Volume: 6.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db 7	; Arpeggio.
	dw -4	; Pitch.

	db 33	; Soft only. Volume: 4.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db 5	; Arpeggio.
	dw 4	; Pitch.

	db 17	; Soft only. Volume: 2.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db 3	; Arpeggio.
	dw -4	; Pitch.

atic_title_Instrument3_Loop	db 9	; Soft only. Volume: 1.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db 1	; Arpeggio.
	dw 3	; Pitch.

	db 9	; Soft only. Volume: 1.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -3	; Pitch.

	db 9	; Soft only. Volume: 1.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 3	; Pitch.

	db 9	; Soft only. Volume: 1.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -3	; Pitch.

	db 7	; Loop.
atic_title_DisarkWordForceReference8
	dw atic_title_Instrument3_Loop	; Loop here.

atic_title_Instrument4
	db 3	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 12	; Arpeggio.

	db 193	; Soft only. Volume: 8. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

atic_title_Instrument4_Loop	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 7	; Loop.
atic_title_DisarkWordForceReference9
	dw atic_title_Instrument4_Loop	; Loop here.

atic_title_Instrument5
	db 4	; The speed (>0, 0 for 256).
	db 225	; Soft only. Volume: 12. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 41	; Soft only. Volume: 5.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 33	; Soft only. Volume: 4.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

atic_title_Instrument5_Loop	db 41	; Soft only. Volume: 5.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 2	; Pitch.

	db 33	; Soft only. Volume: 4.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -2	; Pitch.

	db 7	; Loop.
atic_title_DisarkWordForceReference10
	dw atic_title_Instrument5_Loop	; Loop here.

atic_title_Instrument6
	db 3	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 209	; Soft only. Volume: 10. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

atic_title_Instrument6_Loop	db 57	; Soft only. Volume: 7.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 2	; Pitch.

	db 41	; Soft only. Volume: 5.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 57	; Soft only. Volume: 7.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -2	; Pitch.

	db 41	; Soft only. Volume: 5.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 7	; Loop.
atic_title_DisarkWordForceReference11
	dw atic_title_Instrument6_Loop	; Loop here.

atic_title_Instrument7
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -5	; Arpeggio.

	db 225	; Soft only. Volume: 12. Volume only.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -5	; Arpeggio.

	db 201	; Soft only. Volume: 9. Volume only.

	db 65	; Soft only. Volume: 8.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -5	; Arpeggio.

	db 177	; Soft only. Volume: 6. Volume only.

	db 41	; Soft only. Volume: 5.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 33	; Soft only. Volume: 4.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -5	; Arpeggio.

	db 153	; Soft only. Volume: 3. Volume only.

	db 17	; Soft only. Volume: 2.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 9	; Soft only. Volume: 1.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -5	; Arpeggio.

	db 6	; Loop to silence.

atic_title_Instrument8
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -4	; Arpeggio.

	db 225	; Soft only. Volume: 12. Volume only.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -4	; Arpeggio.

	db 201	; Soft only. Volume: 9. Volume only.

	db 65	; Soft only. Volume: 8.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -4	; Arpeggio.

	db 177	; Soft only. Volume: 6. Volume only.

	db 41	; Soft only. Volume: 5.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 33	; Soft only. Volume: 4.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -4	; Arpeggio.

	db 153	; Soft only. Volume: 3. Volume only.

	db 17	; Soft only. Volume: 2.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 3	; Arpeggio.

	db 9	; Soft only. Volume: 1.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -4	; Arpeggio.

	db 6	; Loop to silence.

atic_title_Instrument9
	db 1	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 113	; Soft only. Volume: 14.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 5	; Arpeggio.

	db 105	; Soft only. Volume: 13.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -3	; Arpeggio.

	db 225	; Soft only. Volume: 12. Volume only.

	db 89	; Soft only. Volume: 11.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 5	; Arpeggio.

	db 81	; Soft only. Volume: 10.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -3	; Arpeggio.

	db 201	; Soft only. Volume: 9. Volume only.

	db 65	; Soft only. Volume: 8.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 5	; Arpeggio.

	db 57	; Soft only. Volume: 7.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -3	; Arpeggio.

	db 177	; Soft only. Volume: 6. Volume only.

	db 41	; Soft only. Volume: 5.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 5	; Arpeggio.

	db 33	; Soft only. Volume: 4.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -3	; Arpeggio.

	db 153	; Soft only. Volume: 3. Volume only.

	db 17	; Soft only. Volume: 2.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db 5	; Arpeggio.

	db 9	; Soft only. Volume: 1.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -3	; Arpeggio.

	db 6	; Loop to silence.

atic_title_Instrument10
	db 3	; The speed (>0, 0 for 256).
	db 193	; Soft only. Volume: 8. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 249	; Soft only. Volume: 15. Volume only.

	db 121	; Soft only. Volume: 15.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 249	; Soft only. Volume: 15. Volume only.

	db 121	; Soft only. Volume: 15.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -2	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 2	; Pitch.

	db 57	; Soft only. Volume: 7.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -3	; Pitch.

	db 65	; Soft only. Volume: 8.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 3	; Pitch.

	db 41	; Soft only. Volume: 5.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -2	; Pitch.

	db 49	; Soft only. Volume: 6.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 2	; Pitch.

atic_title_Instrument10_Loop	db 33	; Soft only. Volume: 4.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -2	; Pitch.

	db 41	; Soft only. Volume: 5.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 2	; Pitch.

	db 7	; Loop.
atic_title_DisarkWordForceReference12
	dw atic_title_Instrument10_Loop	; Loop here.


; The indexes of the effect blocks used by this song.
atic_title_EffectBlockTable
atic_title_DisarkPointerRegionStart13
	dw atic_title_EffectBlock_P28P62	; Index 0
	dw atic_title_EffectBlock_P28P63	; Index 1
	dw atic_title_EffectBlock_P28P66	; Index 2
	dw atic_title_EffectBlock_P28P67	; Index 3
atic_title_DisarkPointerRegionEnd13

atic_title_EffectBlock_P28P62
	db 28, 62
atic_title_EffectBlock_P28P63
	db 28, 63
atic_title_EffectBlock_P28P66
	db 28, 66
atic_title_EffectBlock_P28P67
	db 28, 67

atic_title_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
atic_title_Subsong0_DisarkByteRegionStart0
atic_title_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 4	; Loop start index (>=0).
	db 18	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 17	; Base note index (>=0).

atic_title_Subsong0_Linker
atic_title_Subsong0_DisarkPointerRegionStart1
; Position 0
	dw atic_title_Subsong0_Track0
	dw atic_title_Subsong0_Track1
	dw atic_title_Subsong0_Track11
	dw atic_title_Subsong0_LinkerBlock0

; Position 1
	dw atic_title_Subsong0_Track2
	dw atic_title_Subsong0_Track3
	dw atic_title_Subsong0_Track11
	dw atic_title_Subsong0_LinkerBlock0

; Position 2
	dw atic_title_Subsong0_Track4
	dw atic_title_Subsong0_Track5
	dw atic_title_Subsong0_Track6
	dw atic_title_Subsong0_LinkerBlock1

; Position 3
	dw atic_title_Subsong0_Track4
	dw atic_title_Subsong0_Track5
	dw atic_title_Subsong0_Track6
	dw atic_title_Subsong0_LinkerBlock1

; Position 4
atic_title_Subsong0_Linker_Loop
	dw atic_title_Subsong0_Track0
	dw atic_title_Subsong0_Track1
	dw atic_title_Subsong0_Track7
	dw atic_title_Subsong0_LinkerBlock0

; Position 5
	dw atic_title_Subsong0_Track2
	dw atic_title_Subsong0_Track3
	dw atic_title_Subsong0_Track8
	dw atic_title_Subsong0_LinkerBlock0

; Position 6
	dw atic_title_Subsong0_Track9
	dw atic_title_Subsong0_Track10
	dw atic_title_Subsong0_Track11
	dw atic_title_Subsong0_LinkerBlock1

; Position 7
	dw atic_title_Subsong0_Track9
	dw atic_title_Subsong0_Track10
	dw atic_title_Subsong0_Track11
	dw atic_title_Subsong0_LinkerBlock1

; Position 8
	dw atic_title_Subsong0_Track13
	dw atic_title_Subsong0_Track14
	dw atic_title_Subsong0_Track12
	dw atic_title_Subsong0_LinkerBlock1

; Position 9
	dw atic_title_Subsong0_Track13
	dw atic_title_Subsong0_Track14
	dw atic_title_Subsong0_Track12
	dw atic_title_Subsong0_LinkerBlock1

; Position 10
	dw atic_title_Subsong0_Track13
	dw atic_title_Subsong0_Track14
	dw atic_title_Subsong0_Track15
	dw atic_title_Subsong0_LinkerBlock1

; Position 11
	dw atic_title_Subsong0_Track13
	dw atic_title_Subsong0_Track14
	dw atic_title_Subsong0_Track16
	dw atic_title_Subsong0_LinkerBlock1

; Position 12
	dw atic_title_Subsong0_Track17
	dw atic_title_Subsong0_Track18
	dw atic_title_Subsong0_Track19
	dw atic_title_Subsong0_LinkerBlock0

; Position 13
	dw atic_title_Subsong0_Track17
	dw atic_title_Subsong0_Track18
	dw atic_title_Subsong0_Track19
	dw atic_title_Subsong0_LinkerBlock0

; Position 14
	dw atic_title_Subsong0_Track20
	dw atic_title_Subsong0_Track21
	dw atic_title_Subsong0_Track22
	dw atic_title_Subsong0_LinkerBlock1

; Position 15
	dw atic_title_Subsong0_Track13
	dw atic_title_Subsong0_Track14
	dw atic_title_Subsong0_Track12
	dw atic_title_Subsong0_LinkerBlock1

; Position 16
	dw atic_title_Subsong0_Track13
	dw atic_title_Subsong0_Track14
	dw atic_title_Subsong0_Track12
	dw atic_title_Subsong0_LinkerBlock1

; Position 17
	dw atic_title_Subsong0_Track13
	dw atic_title_Subsong0_Track14
	dw atic_title_Subsong0_Track12
	dw atic_title_Subsong0_LinkerBlock1

; Position 18
	dw atic_title_Subsong0_Track13
	dw atic_title_Subsong0_Track14
	dw atic_title_Subsong0_Track12
	dw atic_title_Subsong0_LinkerBlock1

atic_title_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
atic_title_Subsong0_DisarkWordForceReference2
	dw atic_title_Subsong0_Linker_Loop

atic_title_Subsong0_LinkerBlock0
	db 16	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
atic_title_Subsong0_DisarkWordForceReference3
	dw atic_title_Subsong0_SpeedTrack0	; SpeedTrack address.
atic_title_Subsong0_DisarkWordForceReference4
	dw atic_title_Subsong0_EventTrack0	; EventTrack address.
atic_title_Subsong0_LinkerBlock1
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
atic_title_Subsong0_DisarkWordForceReference5
	dw atic_title_Subsong0_SpeedTrack1	; SpeedTrack address.
atic_title_Subsong0_DisarkWordForceReference6
	dw atic_title_Subsong0_EventTrack0	; EventTrack address.

atic_title_Subsong0_Track0
	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 30
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track1
	db 60	; Waits for 1 line.

	db 154
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 158
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 155
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 25
	db 60	; Waits for 1 line.

	db 26
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track2
	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 36
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track3
	db 60	; Waits for 1 line.

	db 154
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 158
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 155
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 30
	db 60	; Waits for 1 line.

	db 27
	db 60	; Waits for 1 line.

	db 33
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track4
	db 166
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 159
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 167
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 61, 6	; Waits for 7 lines.

	db 155
	db 2	; New Instrument (2).
	db 61, 6	; Waits for 7 lines.

	db 166
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 31
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 32
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 191
	db 73	; Escape note (73).
	db 5	; New Instrument (5).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 157
	db 1	; New Instrument (1).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 191
	db 73	; Escape note (73).
	db 5	; New Instrument (5).
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track5
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 159
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 164
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 160
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 26
	db 61, 6	; Waits for 7 lines.

	db 26
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 159
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 39
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 32
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 27
	db 61, 6	; Waits for 7 lines.

	db 27
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track6
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 167
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 160
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 166
	db 1	; New Instrument (1).
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 159
	db 3	; New Instrument (3).
	db 61, 13	; Waits for 14 lines.

	db 169
	db 1	; New Instrument (1).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 32
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 39
	db 61, 6	; Waits for 7 lines.

	db 191
	db 75	; Escape note (75).
	db 5	; New Instrument (5).
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track7
	db 135
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 2
	db 60	; Waits for 1 line.

	db 0
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 2
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track8
	db 135
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 9
	db 60	; Waits for 1 line.

	db 10
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 15
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 14
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track9
	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 154
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 154
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 154
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 154
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 154
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 154
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track10
	db 135
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 138
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 135
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 138
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 135
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 138
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 141
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 158
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 137
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 158
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 135
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 138
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 135
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 138
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 135
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 138
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 141
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 9	; New Instrument (9).
	db 60	; Waits for 1 line.

	db 142
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 158
	db 7	; New Instrument (7).
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track11
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track12
	db 178
	db 10	; New Instrument (10).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 51
	db 124	; No note, but effects.
	db 2	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 51
	db 124	; No note, but effects.
	db 3	; Index to an effect block.
	db 61, 8	; Waits for 9 lines.

	db 174
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 48
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 53
	db 60	; Waits for 1 line.

	db 51
	db 60	; Waits for 1 line.

	db 50
	db 60	; Waits for 1 line.

	db 46
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 176
	db 10	; New Instrument (10).
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 48
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 48
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 48
	db 124	; No note, but effects.
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 183
	db 4	; New Instrument (4).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 50
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track13
	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 154
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 154
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 154
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 34
	db 60	; Waits for 1 line.

	db 33
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 162
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 162
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 155
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 159
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 154
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 161
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 155
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 31
	db 60	; Waits for 1 line.

	db 26
	db 60	; Waits for 1 line.

	db 161
	db 2	; New Instrument (2).
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track14
	db 135
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 138
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 135
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 138
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 135
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 138
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 141
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 158
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 137
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 158
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 131
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 135
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 131
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 135
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 129
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 137
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 130
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 158
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 134
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 158
	db 8	; New Instrument (8).
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track15
	db 159
	db 6	; New Instrument (6).
	db 61, 6	; Waits for 7 lines.

	db 30
	db 61, 6	; Waits for 7 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 61, 6	; Waits for 7 lines.

	db 33
	db 61, 6	; Waits for 7 lines.

	db 31
	db 61, 6	; Waits for 7 lines.

	db 30
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track16
	db 159
	db 6	; New Instrument (6).
	db 61, 6	; Waits for 7 lines.

	db 30
	db 61, 6	; Waits for 7 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 30
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 34
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 39
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 36
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 42
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 38
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 45
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track17
	db 166
	db 1	; New Instrument (1).
	db 39
	db 36
	db 60	; Waits for 1 line.

	db 34
	db 36
	db 33
	db 60	; Waits for 1 line.

	db 38
	db 39
	db 36
	db 33
	db 34
	db 31
	db 38
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track18
	db 162
	db 1	; New Instrument (1).
	db 36
	db 33
	db 60	; Waits for 1 line.

	db 31
	db 28
	db 30
	db 60	; Waits for 1 line.

	db 31
	db 28
	db 30
	db 26
	db 27
	db 24
	db 26
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track19
	db 135
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 6
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 2
	db 60	; Waits for 1 line.

	db 7
	db 60	; Waits for 1 line.

	db 2
	db 60	; Waits for 1 line.

	db 3
	db 60	; Waits for 1 line.

	db 6
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track20
	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 152
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 152
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 154
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 154
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 155
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 159
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 155
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 161
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 158
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 162
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 159
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 164
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 161
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 162
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 159
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 164
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 161
	db 2	; New Instrument (2).
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track21
	db 128
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 131
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 128
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 131
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 135
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 158
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 138
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 158
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 137
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 158
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 134
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 158
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 128
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 131
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 128
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 131
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 159
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 130
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 161
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 134
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 161
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 137
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 161
	db 8	; New Instrument (8).
	db 60	; Waits for 1 line.

	db 142
	db 6	; New Instrument (6).
	db 60	; Waits for 1 line.

	db 161
	db 8	; New Instrument (8).
	db 61, 127	; Waits for 128 lines.


atic_title_Subsong0_Track22
	db 183
	db 4	; New Instrument (4).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 63
	db 74	; Escape note (74).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 63
	db 75	; Escape note (75).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 63
	db 74	; Escape note (74).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 54
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 63
	db 74	; Escape note (74).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 63
	db 75	; Escape note (75).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 63
	db 74	; Escape note (74).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 63
	db 75	; Escape note (75).
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 63
	db 77	; Escape note (77).
	db 61, 127	; Waits for 128 lines.


; The speed tracks
atic_title_Subsong0_SpeedTrack0
	db 48	; Value: 24.
	db 253	; Wait for 127 lines.
atic_title_Subsong0_SpeedTrack1
	db 12	; Value: 6.
	db 253	; Wait for 127 lines.

; The event tracks
atic_title_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

atic_title_Subsong0_DisarkByteRegionEnd0
