; Sound Effects for song Atic Atac SFX, version 2.0, generated by Arkos Tracker 2.

AticAtacSFX_SoundEffects
AticAtacSFX_SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
AticAtacSFX_SoundEffectsDisarkPointerRegionStart0
	dw AticAtacSFX_SoundEffects_Sound1	; Sound effect 1.
	dw AticAtacSFX_SoundEffects_Sound2	; Sound effect 2.
	dw AticAtacSFX_SoundEffects_Sound3	; Sound effect 3.
	dw AticAtacSFX_SoundEffects_Sound4	; Sound effect 4.
	dw AticAtacSFX_SoundEffects_Sound5	; Sound effect 5.
	dw AticAtacSFX_SoundEffects_Sound6	; Sound effect 6.
	dw AticAtacSFX_SoundEffects_Sound7	; Sound effect 7.
	dw AticAtacSFX_SoundEffects_Sound8	; Sound effect 8.
	dw AticAtacSFX_SoundEffects_Sound9	; Sound effect 9.
	dw AticAtacSFX_SoundEffects_Sound10	; Sound effect 10.
	dw AticAtacSFX_SoundEffects_Sound11	; Sound effect 11.
	dw AticAtacSFX_SoundEffects_Sound12	; Sound effect 12.
AticAtacSFX_SoundEffectsDisarkPointerRegionEnd0

AticAtacSFX_SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
AticAtacSFX_SoundEffects_Sound1
	db 1	; Speed

AticAtacSFX_SoundEffects_Sound1_Loop	db 61	; Soft only. Volume: 15.
	dw 159	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 159	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 150	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 150	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 142	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 142	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 134	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 134	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 127	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 127	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 119	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 119	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 113	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 113	; Software period.

	db 9	; Soft only. Volume: 2.
	dw 106	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 106	; Software period.

	db 4	; End of the sound effect.

; Sound effect 2.
AticAtacSFX_SoundEffects_Sound2
	db 1	; Speed

	db 61	; Soft only. Volume: 15.
	dw 106	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 106	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 113	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 113	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 119	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 119	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 127	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 127	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 134	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 134	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 142	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 142	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 150	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 150	; Software period.

AticAtacSFX_SoundEffects_Sound2_Loop	db 9	; Soft only. Volume: 2.
	dw 159	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 159	; Software period.

	db 4	; End of the sound effect.

; Sound effect 3.
AticAtacSFX_SoundEffects_Sound3
	db 1	; Speed

	db 61	; Soft only. Volume: 15.
	dw 89	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 95	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 100	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 95	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 89	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 95	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 100	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 95	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 89	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 95	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 100	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 95	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 89	; Software period.

	db 9	; Soft only. Volume: 2.
	dw 95	; Software period.

AticAtacSFX_SoundEffects_Sound3_Loop	db 5	; Soft only. Volume: 1.
	dw 100	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 95	; Software period.

	db 4	; End of the sound effect.

; Sound effect 4.
AticAtacSFX_SoundEffects_Sound4
	db 1	; Speed

	db 189	; Soft only. Volume: 15.
	db 31	; Noise: 31.
	dw 159	; Software period.

	db 185	; Soft only. Volume: 14.
	db 31	; Noise: 31.
	dw 169	; Software period.

	db 161	; Soft only. Volume: 8.
	db 31	; Noise: 31.
	dw 190	; Software period.

	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 213	; Software period.

	db 181	; Soft only. Volume: 13.
	db 31	; Noise: 31.
	dw 225	; Software period.

	db 153	; Soft only. Volume: 6.
	db 31	; Noise: 31.
	dw 253	; Software period.

	db 177	; Soft only. Volume: 12.
	db 31	; Noise: 31.
	dw 268	; Software period.

	db 173	; Soft only. Volume: 11.
	db 31	; Noise: 31.
	dw 301	; Software period.

	db 169	; Soft only. Volume: 10.
	db 31	; Noise: 31.
	dw 319	; Software period.

	db 149	; Soft only. Volume: 5.
	db 31	; Noise: 31.
	dw 338	; Software period.

	db 165	; Soft only. Volume: 9.
	db 31	; Noise: 31.
	dw 379	; Software period.

	db 145	; Soft only. Volume: 4.
	db 31	; Noise: 31.
	dw 402	; Software period.

	db 161	; Soft only. Volume: 8.
	db 31	; Noise: 31.
	dw 451	; Software period.

	db 141	; Soft only. Volume: 3.
	db 31	; Noise: 31.
	dw 478	; Software period.

AticAtacSFX_SoundEffects_Sound4_Loop	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 506	; Software period.

	db 137	; Soft only. Volume: 2.
	db 31	; Noise: 31.
	dw 568	; Software period.

	db 133	; Soft only. Volume: 1.
	db 31	; Noise: 31.
	dw 602	; Software period.

	db 129	; Soft only. Volume: 0.
	db 31	; Noise: 31.
	dw 638	; Software period.

	db 4	; End of the sound effect.

; Sound effect 5.
AticAtacSFX_SoundEffects_Sound5
	db 1	; Speed

	db 189	; Soft only. Volume: 15.
	db 31	; Noise: 31.
	dw 239	; Software period.

	db 161	; Soft only. Volume: 8.
	db 31	; Noise: 31.
	dw 268	; Software period.

	db 185	; Soft only. Volume: 14.
	db 31	; Noise: 31.
	dw 301	; Software period.

	db 181	; Soft only. Volume: 13.
	db 31	; Noise: 31.
	dw 319	; Software period.

	db 177	; Soft only. Volume: 12.
	db 31	; Noise: 31.
	dw 379	; Software period.

	db 153	; Soft only. Volume: 6.
	db 31	; Noise: 31.
	dw 402	; Software period.

	db 173	; Soft only. Volume: 11.
	db 31	; Noise: 31.
	dw 426	; Software period.

	db 169	; Soft only. Volume: 10.
	db 31	; Noise: 31.
	dw 426	; Software period.

	db 149	; Soft only. Volume: 5.
	db 31	; Noise: 31.
	dw 451	; Software period.

	db 145	; Soft only. Volume: 4.
	db 31	; Noise: 31.
	dw 478	; Software period.

	db 165	; Soft only. Volume: 9.
	db 31	; Noise: 31.
	dw 536	; Software period.

	db 141	; Soft only. Volume: 3.
	db 31	; Noise: 31.
	dw 536	; Software period.

	db 161	; Soft only. Volume: 8.
	db 31	; Noise: 31.
	dw 568	; Software period.

	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 638	; Software period.

AticAtacSFX_SoundEffects_Sound5_Loop	db 137	; Soft only. Volume: 2.
	db 31	; Noise: 31.
	dw 676	; Software period.

	db 153	; Soft only. Volume: 6.
	db 31	; Noise: 31.
	dw 676	; Software period.

	db 133	; Soft only. Volume: 1.
	db 31	; Noise: 31.
	dw 716	; Software period.

	db 129	; Soft only. Volume: 0.
	db 31	; Noise: 31.
	dw 758	; Software period.

	db 4	; End of the sound effect.

; Sound effect 6.
AticAtacSFX_SoundEffects_Sound6
	db 1	; Speed

	db 189	; Soft only. Volume: 15.
	db 31	; Noise: 31.
	dw 358	; Software period.

	db 185	; Soft only. Volume: 14.
	db 31	; Noise: 31.
	dw 379	; Software period.

	db 181	; Soft only. Volume: 13.
	db 31	; Noise: 31.
	dw 402	; Software period.

	db 161	; Soft only. Volume: 8.
	db 31	; Noise: 31.
	dw 426	; Software period.

	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 451	; Software period.

	db 177	; Soft only. Volume: 12.
	db 31	; Noise: 31.
	dw 478	; Software period.

	db 173	; Soft only. Volume: 11.
	db 31	; Noise: 31.
	dw 506	; Software period.

	db 153	; Soft only. Volume: 6.
	db 31	; Noise: 31.
	dw 536	; Software period.

	db 169	; Soft only. Volume: 10.
	db 31	; Noise: 31.
	dw 568	; Software period.

	db 149	; Soft only. Volume: 5.
	db 31	; Noise: 31.
	dw 602	; Software period.

	db 165	; Soft only. Volume: 9.
	db 31	; Noise: 31.
	dw 638	; Software period.

	db 161	; Soft only. Volume: 8.
	db 31	; Noise: 31.
	dw 676	; Software period.

	db 145	; Soft only. Volume: 4.
	db 31	; Noise: 31.
	dw 716	; Software period.

	db 141	; Soft only. Volume: 3.
	db 31	; Noise: 31.
	dw 758	; Software period.

AticAtacSFX_SoundEffects_Sound6_Loop	db 137	; Soft only. Volume: 2.
	db 31	; Noise: 31.
	dw 804	; Software period.

	db 157	; Soft only. Volume: 7.
	db 31	; Noise: 31.
	dw 851	; Software period.

	db 133	; Soft only. Volume: 1.
	db 31	; Noise: 31.
	dw 902	; Software period.

	db 129	; Soft only. Volume: 0.
	db 31	; Noise: 31.
	dw 956	; Software period.

	db 4	; End of the sound effect.

; Sound effect 7.
AticAtacSFX_SoundEffects_Sound7
	db 1	; Speed

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 60	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 60	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 60	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 60	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 60	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 60	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 60	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 60	; Software period.

	db 189	; Soft only. Volume: 15.
	db 1	; Noise: 1.
	dw 60	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 60	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 60	; Software period.

AticAtacSFX_SoundEffects_Sound7_Loop	db 1	; Soft only. Volume: 0.
	dw 60	; Software period.

	db 4	; End of the sound effect.

; Sound effect 8.
AticAtacSFX_SoundEffects_Sound8
	db 0	; Speed

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 119	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 119	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 119	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 119	; Software period.

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 239	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 239	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 239	; Software period.

AticAtacSFX_SoundEffects_Sound8_Loop	db 1	; Soft only. Volume: 0.
	dw 239	; Software period.

	db 4	; End of the sound effect.

; Sound effect 9.
AticAtacSFX_SoundEffects_Sound9
	db 4	; Speed

	db 61	; Soft only. Volume: 15.
	dw 36	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 38	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 40	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 42	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 45	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 47	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 50	; Software period.

	db 33	; Soft only. Volume: 8.
	dw 53	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 56	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 60	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 63	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 67	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 71	; Software period.

	db 9	; Soft only. Volume: 2.
	dw 75	; Software period.

AticAtacSFX_SoundEffects_Sound9_Loop	db 5	; Soft only. Volume: 1.
	dw 80	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 84	; Software period.

	db 4	; End of the sound effect.

; Sound effect 10.
AticAtacSFX_SoundEffects_Sound10
	db 0	; Speed

	db 129	; Soft only. Volume: 0.
	db 7	; Noise: 7.
	dw 338	; Software period.

	db 5	; Soft only. Volume: 1.
	dw 338	; Software period.

	db 137	; Soft only. Volume: 2.
	db 6	; Noise: 6.
	dw 319	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 319	; Software period.

	db 145	; Soft only. Volume: 4.
	db 5	; Noise: 5.
	dw 301	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 301	; Software period.

	db 153	; Soft only. Volume: 6.
	db 4	; Noise: 4.
	dw 284	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 284	; Software period.

	db 161	; Soft only. Volume: 8.
	db 3	; Noise: 3.
	dw 268	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 268	; Software period.

	db 169	; Soft only. Volume: 10.
	db 2	; Noise: 2.
	dw 253	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 253	; Software period.

	db 177	; Soft only. Volume: 12.
	db 1	; Noise: 1.
	dw 239	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 239	; Software period.

AticAtacSFX_SoundEffects_Sound10_Loop	db 57	; Soft only. Volume: 14.
	dw 225	; Software period.

	db 61	; Soft only. Volume: 15.
	dw 225	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 338	; Software period.

	db 4	; End of the sound effect.

; Sound effect 11.
AticAtacSFX_SoundEffects_Sound11
	db 1	; Speed

	db 61	; Soft only. Volume: 15.
	dw 225	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 225	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 150	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 150	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 225	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 225	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 301	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 301	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 225	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 225	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 150	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 150	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 225	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 225	; Software period.

AticAtacSFX_SoundEffects_Sound11_Loop	db 5	; Soft only. Volume: 1.
	dw 301	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 301	; Software period.

	db 4	; End of the sound effect.

; Sound effect 12.
AticAtacSFX_SoundEffects_Sound12
	db 1	; Speed

	db 61	; Soft only. Volume: 15.
	dw 179	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 179	; Software period.

	db 57	; Soft only. Volume: 14.
	dw 119	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 119	; Software period.

	db 53	; Soft only. Volume: 13.
	dw 179	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 179	; Software period.

	db 49	; Soft only. Volume: 12.
	dw 239	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 239	; Software period.

	db 45	; Soft only. Volume: 11.
	dw 179	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 179	; Software period.

	db 41	; Soft only. Volume: 10.
	dw 119	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 119	; Software period.

	db 37	; Soft only. Volume: 9.
	dw 179	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 179	; Software period.

AticAtacSFX_SoundEffects_Sound12_Loop	db 33	; Soft only. Volume: 8.
	dw 239	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 239	; Software period.

	db 29	; Soft only. Volume: 7.
	dw 179	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 179	; Software period.

	db 25	; Soft only. Volume: 6.
	dw 119	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 119	; Software period.

	db 21	; Soft only. Volume: 5.
	dw 179	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 179	; Software period.

	db 17	; Soft only. Volume: 4.
	dw 239	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 239	; Software period.

	db 13	; Soft only. Volume: 3.
	dw 179	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 179	; Software period.

	db 9	; Soft only. Volume: 2.
	dw 119	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 119	; Software period.

	db 5	; Soft only. Volume: 1.
	dw 179	; Software period.

	db 1	; Soft only. Volume: 0.
	dw 179	; Software period.

	db 4	; End of the sound effect.

AticAtacSFX_SoundEffectsDisarkByteRegionEnd1
