org 0x100

code_start

include "utils/start.asm"
include "utils/constants.asm"
include "utils/screen_size.asm"
include "utils/utils.asm"

include "lines.asm"
include "draw_room.asm"
include "draw_items.asm"
include "panel.asm"
include "player.asm"
include "collision.asm"
include "interrupts.asm"
include "keyboard.asm"
include "falling.asm"
include "font.asm"
include "chicken.asm"
include "menu.asm"
include "clock.asm"
include "fonts/textstrings.asm"
include "collectables.asm"
include "data/pickup_data.asm"
include "sound.asm"
include "transients.asm"
include "data/transient_data.asm"
include "sprite.asm"
include "weapons.asm"
include "setup.asm"
include "state_manager.asm"
include "game.asm"
