org 0x100

code_start

include "utils/start.asm"
include "utils/constants.asm"
include "utils/screen_size.asm"
include "utils/utils.asm"
include "macros.asm"

include "lines.asm"
include "room.asm"
include "items.asm"
include "panel.asm"
include "player.asm"
include "playermove.asm"
include "doors.asm"
include "doormap.asm"
include "interrupts.asm"
include "keyboard.asm"
include "falling.asm"
include "font.asm"
include "chicken.asm"
include "menu.asm"

include "clock.asm"
include "fonts/textstrings.asm"
include "collectables.asm"
include "data/pickup_data.asm"
include "sound.asm"
include "food.asm"
include "sprite.asm"
include "weapon.asm"
include "boss.asm"
include "setup.asm"
include "endgame.asm"
include "state_manager.asm"
include "game.asm"
